## The dataset

We will use the Online Retail II Data Set available in the [UCI Machine Learning Repository](http://archive.ics.uci.edu/dataset/502/online+retail+ii).


**Citation**:

Dua, D. and Graff, C. (2019). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

## Features from the date part:

Below are some of the features that we can extract from the date part of the datetime variable off-the-shelf using [pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#time-date-components):


- pandas.Series.dt.year
- pandas.Series.dt.quarter
- pandas.Series.dt.month
- pandas.Series.dt.isocalendar().week
- pandas.Series.dt.day
- pandas.Series.dt.day_of_week
- pandas.Series.dt.weekday
- pandas.Series.dt.dayofyear
- pandas.Series.dt.day_of_year

- pandas.Series.dt.is_month_start
- pandas.Series.dt.is_month_end
- pandas.Series.dt.is_quarter_start
- pandas.Series.dt.is_quarter_end
- pandas.Series.dt.is_year_start
- pandas.Series.dt.is_year_end
- pandas.Series.dt.is_leap_year
- pandas.Series.dt.days_in_month

We can use the features obtained with pandas to create even more features, such as:

- Semester
- Is Weekend?

In [1]:
import numpy as np 
import pandas as pd

In [2]:
file_path = "../data/online_retail_II.xlsx"
df_1 = pd.read_excel(file_path, sheet_name="Year 2009-2010")
df_2 = pd.read_excel(file_path, sheet_name="Year 2010-2011")

data = pd.concat([df_1, df_2])

print(data.shape)

data.head()

(1067371, 8)


Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12   
1  489434    79323P                   PINK CHERRY LIGHTS        12   
2  489434    79323W                  WHITE CHERRY LIGHTS        12   
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48   
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24   

          InvoiceDate  Price  Customer ID         Country  
0 2009-12-01 07:45:00   6.95      13085.0  United Kingdom  
1 2009-12-01 07:45:00   6.75      13085.0  United Kingdom  
2 2009-12-01 07:45:00   6.75      13085.0  United Kingdom  
3 2009-12-01 07:45:00   2.10      13085.0  United Kingdom  
4 2009-12-01 07:45:00   1.25      13085.0  United Kingdom

## Variable format

In [3]:
data['InvoiceDate'].dtypes

dtype('<M8[ns]')

`InvoiceData` is already parsed as datetime data, but incase it was not, usually,we can use `pd.to_dateime` method to cast the vars (mostly in object dtype) to datetime

In [4]:
data["date"] = pd.to_datetime(data["InvoiceDate"])
data[["date", "InvoiceDate"]].dtypes

date           datetime64[ns]
InvoiceDate    datetime64[ns]
dtype: object

In [5]:
data[["date", "InvoiceDate"]].head()

date         InvoiceDate
0 2009-12-01 07:45:00 2009-12-01 07:45:00
1 2009-12-01 07:45:00 2009-12-01 07:45:00
2 2009-12-01 07:45:00 2009-12-01 07:45:00
3 2009-12-01 07:45:00 2009-12-01 07:45:00
4 2009-12-01 07:45:00 2009-12-01 07:45:00

## Date and time parts

The date and time parts of the datetime vars are not useful for predictions, but they may be handy for data analysis.

In [6]:
# Extract the date part
data["date_part"] = data["date"].dt.date
data["date_part"].head()

0    2009-12-01
1    2009-12-01
2    2009-12-01
3    2009-12-01
4    2009-12-01
Name: date_part, dtype: object

In [7]:
# Extract the time part
data["time_part"] = data["date"].dt.time
data["time_part"].head()

0    07:45:00
1    07:45:00
2    07:45:00
3    07:45:00
4    07:45:00
Name: time_part, dtype: object

## Features derived from date


### Year

In [8]:
# Extract year
data["invoice_year"] = data["date"].dt.year
print(data[["date_part", "invoice_year"]].head())
print(data["invoice_year"].unique())

    date_part  invoice_year
0  2009-12-01          2009
1  2009-12-01          2009
2  2009-12-01          2009
3  2009-12-01          2009
4  2009-12-01          2009
[2009 2010 2011]


### Year start and end

In [9]:
# Is the date year start or end

data["invoice_year_start"] = data["date"].dt.is_year_start
data["invoice_year_end"] = data["date"].dt.is_year_end
data[["date", "invoice_year_start", "invoice_year_end"]].head()

date  invoice_year_start  invoice_year_end
0 2009-12-01 07:45:00               False             False
1 2009-12-01 07:45:00               False             False
2 2009-12-01 07:45:00               False             False
3 2009-12-01 07:45:00               False             False
4 2009-12-01 07:45:00               False             False

In [10]:
data["invoice_year_start"].unique()

array([False])

In [11]:
data["invoice_year_end"].unique()

array([False])

With those analyses aboved, we can see that there are no sales on the first and last day of the year.

### Leap year

In [12]:
data["invoice_year_leap"] = data["date"].dt.is_leap_year
data[["date", "invoice_year_leap"]].head()

date  invoice_year_leap
0 2009-12-01 07:45:00              False
1 2009-12-01 07:45:00              False
2 2009-12-01 07:45:00              False
3 2009-12-01 07:45:00              False
4 2009-12-01 07:45:00              False

In [13]:
data["invoice_year_leap"].unique()

array([False])

None of 2009, 2010, 2011 is leap year

### Extract quarter

In [14]:
data["invoice_quarter"] = data["date"].dt.quarter
print(data[["date", "invoice_quarter"]].head())
print(data["invoice_quarter"].unique())

                 date  invoice_quarter
0 2009-12-01 07:45:00                4
1 2009-12-01 07:45:00                4
2 2009-12-01 07:45:00                4
3 2009-12-01 07:45:00                4
4 2009-12-01 07:45:00                4
[4 1 2 3]


### Quarter start and end

In [15]:
data["invoice_quarter_start"] = data["date"].dt.is_quarter_start
data["invoice_quarter_end"] = data["date"].dt.is_quarter_end
print(
    data[["date", "invoice_quarter_start", "invoice_quarter_end"]]\
    .head()
)
print(data["invoice_quarter_start"].unique())

                 date  invoice_quarter_start  invoice_quarter_end
0 2009-12-01 07:45:00                  False                False
1 2009-12-01 07:45:00                  False                False
2 2009-12-01 07:45:00                  False                False
3 2009-12-01 07:45:00                  False                False
4 2009-12-01 07:45:00                  False                False
[False  True]


In [16]:
# sanity check if quarter start is true
data[data["invoice_quarter_start"]].head()

Invoice StockCode                          Description  Quantity  \
147682  503430     21523  DOOR MAT FANCY FONT HOME SWEET HOME        10   
147683  503430     21524      DOOR MAT SPOTTY HOME SWEET HOME        10   
147684  503430     48116          DOOR MAT MULTICOLOUR STRIPE        10   
147685  503430     48129                     DOOR MAT TOPIARY        10   
147686  503430     48187                 DOOR MAT NEW ENGLAND        10   

               InvoiceDate  Price  Customer ID         Country  \
147682 2010-04-01 07:49:00   6.35      13361.0  United Kingdom   
147683 2010-04-01 07:49:00   6.35      13361.0  United Kingdom   
147684 2010-04-01 07:49:00   6.35      13361.0  United Kingdom   
147685 2010-04-01 07:49:00   6.35      13361.0  United Kingdom   
147686 2010-04-01 07:49:00   6.35      13361.0  United Kingdom   

                      date   date_part time_part  invoice_year  \
147682 2010-04-01 07:49:00  2010-04-01  07:49:00          2010   
147683 2010-04-01 07:49:00  2010-04-01  07:49:00          2010   
147684 2010-04-01 07:49:00  2010-04-01  07:49:00          2010   
147685 2010-04-01 07:49:00  2010-04-01  07:49:00          2010   
147686 2010-04-01 07:49:00  2010-04-01  07:49:00          2010   

        invoice_year_start  invoice_year_end  invoice_year_leap  \
147682               False             False              False   
147683               False             False              False   
147684               False             False              False   
147685               False             False              False   
147686               False             False              False   

        invoice_quarter  invoice_quarter_start  invoice_quarter_end  
147682                2                   True                False  
147683                2                   True                False  
147684                2                   True                False  
147685                2                   True                False  
147686                2                   True                False

### Extract semester

In [17]:
data["invoice_semester"] = np.where(data["invoice_quarter"].isin([1,2]), 1, 2)
data[["invoice_quarter", "invoice_semester"]].head()

invoice_quarter  invoice_semester
0                4                 2
1                4                 2
2                4                 2
3                4                 2
4                4                 2

In [18]:
data["invoice_semester"].unique()

array([2, 1])

### Extract month

In [19]:
# Extract month - 1 to 12
data["invoice_month"] = data["date"].dt.month
data[["date", "invoice_month"]].head()

date  invoice_month
0 2009-12-01 07:45:00             12
1 2009-12-01 07:45:00             12
2 2009-12-01 07:45:00             12
3 2009-12-01 07:45:00             12
4 2009-12-01 07:45:00             12

In [ ]:
data["invoice_month"].unique()

<bound method Series.unique of 0         12
1         12
2         12
3         12
4         12
          ..
541905    12
541906    12
541907    12
541908    12
541909    12
Name: invoice_month, Length: 1067371, dtype: int32>

### Days in month

In [21]:
# number of days in a month
data["days_in_month"] = data["date"].dt.days_in_month
data[["invoice_month", "days_in_month"]].head()

invoice_month  days_in_month
0             12             31
1             12             31
2             12             31
3             12             31
4             12             31

In [22]:
data["days_in_month"].unique()

array([31, 28, 30], dtype=int32)

Month start and end

In [23]:
# Extract month start and end
data["invoice_month_start"] = data["date"].dt.is_month_start
data["invoice_month_end"] = data["date"].dt.is_month_end

print(data[["date", "invoice_month_start", "invoice_month_end"]].head())
print(data["invoice_month_start"].unique())

                 date  invoice_month_start  invoice_month_end
0 2009-12-01 07:45:00                 True              False
1 2009-12-01 07:45:00                 True              False
2 2009-12-01 07:45:00                 True              False
3 2009-12-01 07:45:00                 True              False
4 2009-12-01 07:45:00                 True              False
[ True False]


## Week of the year

In [24]:
# Extract week of the year - from 1 to 52
data["invoice_week"] = data["date"].dt.isocalendar().week
print(data[["date", "invoice_week"]].head())
print(data["invoice_week"].unique())

                 date  invoice_week
0 2009-12-01 07:45:00            49
1 2009-12-01 07:45:00            49
2 2009-12-01 07:45:00            49
3 2009-12-01 07:45:00            49
4 2009-12-01 07:45:00            49
<IntegerArray>
[49, 50, 51, 52,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]
Length: 52, dtype: UInt32


## Day of the month (1-31)

In [27]:
data["invoice_day"] = data["date"].dt.day
print(data[["date", "invoice_day"]].head())
print(data["invoice_day"].unique())

                 date  invoice_day
0 2009-12-01 07:45:00            1
1 2009-12-01 07:45:00            1
2 2009-12-01 07:45:00            1
3 2009-12-01 07:45:00            1
4 2009-12-01 07:45:00            1
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18 20 21 22 23 12 19 24
 25 26 27 28 29 31 30]


### Day of the week (0-6 (mon-sun))

In [28]:
data["invoice_dayofweek"] = data["date"].dt.day_of_week
print(data[["date", "invoice_dayofweek"]].head())
print(data["invoice_dayofweek"].unique())

                 date  invoice_dayofweek
0 2009-12-01 07:45:00                  1
1 2009-12-01 07:45:00                  1
2 2009-12-01 07:45:00                  1
3 2009-12-01 07:45:00                  1
4 2009-12-01 07:45:00                  1
[1 2 3 4 5 6 0]


### Day of the week (string - like Monday - Sunday)

In [ ]:

data["invoice_day_name"] = data["date"].dt.day_name()
print(data[["date", "invoice_day_name"]].head())
print(data["invoice_day_name"].unique())

                 date invoice_day_name
0 2009-12-01 07:45:00          Tuesday
1 2009-12-01 07:45:00          Tuesday
2 2009-12-01 07:45:00          Tuesday
3 2009-12-01 07:45:00          Tuesday
4 2009-12-01 07:45:00          Tuesday
['Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday' 'Sunday' 'Monday']


### Was an invoice issued on weekend?

In [32]:
data["is_weekend"] = data["date"].dt.day_of_week > 4
print(data[["date", "invoice_day_name", "is_weekend"]].head())
print(data["is_weekend"].unique())

                 date invoice_day_name  is_weekend
0 2009-12-01 07:45:00          Tuesday       False
1 2009-12-01 07:45:00          Tuesday       False
2 2009-12-01 07:45:00          Tuesday       False
3 2009-12-01 07:45:00          Tuesday       False
4 2009-12-01 07:45:00          Tuesday       False
[False  True]


### Day of the year (1-365)

In [33]:
data["invoice_day_year"] = data["date"].dt.dayofyear
print(data[["date", "invoice_day_year"]].head())
print(data["invoice_day_year"].agg(["min", "max"]))

                 date  invoice_day_year
0 2009-12-01 07:45:00               335
1 2009-12-01 07:45:00               335
2 2009-12-01 07:45:00               335
3 2009-12-01 07:45:00               335
4 2009-12-01 07:45:00               335
min      4
max    357
Name: invoice_day_year, dtype: int32
